### ISSUE TITLE
Use an Azure Pipeline configuration file

### ISSUE THREAD

**Issue by Shtong** [abergs/fido2-net-lib#126]
**Suggestion**: Use YAML Pipelines to build and deploy the project, instead of the classic web interface configuration

**Reasoning**: Azure Pipelines now provides (and recommends) a new way to configure the build and release process. It uses a YAML file stored in the built project's repo, instead of defining it using the DevOps web interface (now called "classic" mode).

Using this mechanism has several advantages : 
- It allows contributors to update the build process as part of their pull request (for example it would have been useful in #124 to update the target SDK version)
- Branches can use a build configuration that is specific to them, without breaking the build for the other branches
- The full build configuration is now in a file in the GIT repo, making it easier to access

**Comment by abergs** [comment]
I agree with the reasoning. I believe the configuration can be extracted from the interface.

**Comment by Shtong** [comment]
It is possible. The result usually needs a little bit of cleanup but it's pretty simple overall!

**Comment by Shtong** [comment]
I've tried to have a look at this but I don't have the permissions to look at and export the pipeline's YAML files. So someone with enough permissions will have to do it :)

**Comment by abergs** [comment]
Exported YAML:

#


# Fido2 Demo Build

```
pool:
  name: Hosted VS2017
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.101'
  inputs:
    version: 2.2.101

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: 'dotnet build entire sln'
  inputs:
    command: publish
    arguments: '--configuration $(BuildConfiguration) --output $(build.ArtifactStagingDirectory) --framework netcoreapp2.2'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: demodrop'
  inputs:
    ArtifactName: demodrop
```



# Fido2-CI
```
pool:
  name: Hosted VS2017
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.101'
  inputs:
    version: 2.2.101

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

- task: PowerShell@2
  displayName: 'Run build script (lib only, release mode)'
  inputs:
    targetType: filePath
    filePath: ./scripts/buildRelease.ps1
    arguments: '"-p:Version=$(Build.BuildNumber)-development"'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
```


## Fido2 Tests

```
pool:
  name: Hosted VS2017
steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.101'
  inputs:
    version: 2.2.101

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: 'fido2-net-lib.Test/*.csproj'

```
